# Generated by Django 5.2.2 on 2025-06-11 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('notifications', models.TextField(blank=True)),
                ('required_teachers', models.ManyToManyField(related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
