# Generated by Django 5.2.2 on 2025-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examcategory_exam_is_closed_exam_is_ecos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_ecos',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='required_teachers',
        ),
        migrations.AddField(
            model_name='exam',
            name='required_teachers_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Required Teachers'),
        ),
    ]
