# Generated by Django 5.2.2 on 2025-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_exam_is_closed_remove_exam_is_ecos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='promotion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Salle/Amphi'),
        ),
    ]
