# Generated by Django 5.2.2 on 2025-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_promotion_alter_exam_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='titre',
            field=models.CharField(default='Titre à renseigner', max_length=200, verbose_name="Titre de l'épreuve"),
        ),
    ]
