# Generated by Django 5.2.2 on 2025-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(verbose_name='Durée (minutes)'),
        ),
    ]
