# Generated by Django 5.2.2 on 2025-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docimology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docimologysession',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='is_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='is_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
