# Generated by Django 5.2.2 on 2025-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docimology', '0002_docimologysession_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docimologysession',
            name='date_examen',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'examen"),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='is_distanciel',
            field=models.BooleanField(default=False, verbose_name='Distanciel'),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='nb_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité de questions'),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='programme',
            field=models.TextField(blank=True, verbose_name='Programme de la séance'),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='responsable1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable n°1 de la séance'),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='responsable2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable n°2 de la séance'),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='salle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Salle de la réunion'),
        ),
        migrations.AddField(
            model_name='docimologysession',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spécialité concernée'),
        ),
    ]
