# Generated by Django 5.2.2 on 2025-06-17 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docimology', '0003_docimologysession_date_examen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docimologysession',
            name='required_teachers_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de professeurs requis'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docimologysession',
            name='responsable1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docimology_responsable1', to=settings.AUTH_USER_MODEL, verbose_name='Responsable n°1 de la séance'),
        ),
        migrations.AlterField(
            model_name='docimologysession',
            name='responsable2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docimology_responsable2', to=settings.AUTH_USER_MODEL, verbose_name='Responsable n°2 de la séance'),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='docimology.docimologysession'),
        ),
    ]
