# Generated by Django 5.2.2 on 2025-06-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docimology', '0004_docimologysession_required_teachers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docimologysession',
            name='teacher',
        ),
    ]
